# install Nginx using Ansible
- name: Setup nginx server on myserver list (host group)
  hosts: myservers
  vars:
    base_path: /home/ec2-user
  tasks: 
    - name: Install the latest version of nginx
      command: sudo yum install nginx -y
  
    - name: Start nginx service
      service:
        name: nginx
        state: started

    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes

    - name: Get nginx installed version
      command: nginx -v
      register: nginx_version

    - name: Print version of nginx
      degun:
        msg: "The current version of nginx is: {{nginx_version.stderr_lines[0]}}"

    - name: Get status of nginx service
      command: systemctl status nginx

    - name: Ansible copy file to remote server
      copy: 
        src: /root/sample2.txt
        dest: {{ base_path }}